import type { CourseRecord } from "./course.types";

export const mockCourses: CourseRecord[] = [
   {
    id: "c1",
    courseName: "Toán 12 Luyện đề 2027",
    subject: "Mathematics",
    grade: 12,
    description: "Khóa học luyện đề chuyên sâu giúp học sinh ôn tập và chinh phục kỳ thi THPT Quốc gia.",
    thumbnail: "",
    tuitionFee: 2500000,
    durationWeeks: 10,
    totalLessons: 40,
    target: "Học sinh lớp 12 có mục tiêu xét tuyển đại học",
    status: "Published",
    createdAt: "2025-01-15T08:00:00.000Z",
    updatedAt: "2025-01-15T08:00:00.000Z",
  },
  {
    id: "c2",
    courseName: "Vật lý 12 Nâng cao",
    subject: "Physics",
    grade: 12,
    description: "Ôn tập kiến thức trọng tâm và rèn luyện kỹ năng giải các dạng bài vận dụng, vận dụng cao.",
    thumbnail: "",
    tuitionFee: 2200000,
    durationWeeks: 8,
    totalLessons: 32,
    target: "Học sinh cần nâng cao tư duy và kỹ năng giải bài tập Vật lý",
    status: "Draft",
    createdAt: "2025-02-20T09:30:00.000Z",
    updatedAt: "2025-02-20T09:30:00.000Z",
  },
  {
    id: "c3",
    courseName: "Tiếng Anh 12 Toàn diện",
    subject: "English",
    grade: 12,
    description: "Luyện ngữ pháp, từ vựng, kỹ năng đọc hiểu và viết theo cấu trúc đề thi THPT Quốc gia.",
    thumbnail: "",
    tuitionFee: 1800000,
    durationWeeks: 6,
    totalLessons: 24,
    target: "Học sinh muốn cải thiện điểm môn Tiếng Anh trong kỳ thi tốt nghiệp",
    status: "Closed",
    createdAt: "2024-11-10T07:45:00.000Z",
    updatedAt: "2024-11-10T07:45:00.000Z",
  },
];
