import type { CourseRecord } from "./course.types";

export const mockCourses: CourseRecord[] = [
    {
        id: "c1",
        courseName: "Mathematics 12 Intensive 2027",
        subject: "Mathematics",
        grade: 12,
        description: "Intensive preparation course for the national exam.",
        thumbnail: "",
        tuitionFee: 2500000,
        durationWeeks: 10,
        totalLessons: 40,
        target: "Grade 12 students aiming for university admission",
        status: "Published",
        createdAt: "2025-01-15T08:00:00.000Z",
        updatedAt: "2025-01-15T08:00:00.000Z",
    },
    {
        id: "c2",
        courseName: "Physics 12 Advanced",
        subject: "Physics",
        grade: 12,
        description: "Concept-based advanced physics preparation.",
        thumbnail: "",
        tuitionFee: 2200000,
        durationWeeks: 8,
        totalLessons: 32,
        target: "Students needing higher-level problem solving",
        status: "Draft",
        createdAt: "2025-02-20T09:30:00.000Z",
        updatedAt: "2025-02-20T09:30:00.000Z",
    },
    {
        id: "c3",
        courseName: "English 12 Speaking & Writing",
        subject: "English",
        grade: 12,
        description: "Focused speaking and writing practice for the exam.",
        thumbnail: "",
        tuitionFee: 1800000,
        durationWeeks: 6,
        totalLessons: 24,
        target: "Students improving comprehension and writing",
        status: "Closed",
        createdAt: "2024-11-10T07:45:00.000Z",
        updatedAt: "2024-11-10T07:45:00.000Z",
    }
];
