import type { CourseRecord } from "./course.types";

export const mockCourses: CourseRecord[] = [
  {
    id: "c1",
    name: "Mathematics 12 Intensive 2027",
    code: "MATH12",
    level: "ADVANCED",
    subjectId: { _id: "1", name: "Toán", code: "TOAN", status: "ACTIVE", createdAt: "", updatedAt: "" },
    grade: 12,
    description: "Intensive preparation course for the national exam.",
    thumbnail: "",
    pricing: { tuitionFee: 2500000 },
    duration: { value: 10, unit: "WEEK" },
    status: "PUBLISHED",
    createdAt: "2025-01-15T08:00:00.000Z",
    updatedAt: "2025-01-15T08:00:00.000Z",
  },
  {
    id: "c2",
    name: "Physics 12 Advanced",
    code: "PHY12",
    level: "INTERMEDIATE",
    subjectId: { _id: "2", name: "Vật lý", code: "LY", status: "ACTIVE", createdAt: "", updatedAt: "" },
    grade: 12,
    description: "Concept-based advanced physics preparation.",
    thumbnail: "",
    pricing: { tuitionFee: 2200000 },
    duration: { value: 8, unit: "WEEK" },
    status: "DRAFT",
    createdAt: "2025-02-20T09:30:00.000Z",
    updatedAt: "2025-02-20T09:30:00.000Z",
  },
  {
    id: "c3",
    name: "English 12 Speaking & Writing",
    code: "ENG12",
    level: "FOUNDATION",
    subjectId: { _id: "3", name: "Hóa học", code: "HOA", status: "ACTIVE", createdAt: "", updatedAt: "" },
    grade: 12,
    description: "Focused speaking and writing practice for the exam.",
    thumbnail: "",
    pricing: { tuitionFee: 1800000 },
    duration: { value: 6, unit: "WEEK" },
    status: "ARCHIVED",
    createdAt: "2024-11-10T07:45:00.000Z",
    updatedAt: "2024-11-10T07:45:00.000Z",
  },
];
